services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"

  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - app
    command: pytest -v -s tests.py


  runner:
    depends_on:
      - app
    build: ./
    container_name: runner
    command: python log_start.py