name: App Runner

on:
  push:        # запуск при пуше
    branches:
      - main
  pull_request:  # запуск при PR
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Start services and run tests
        run: |
          docker compose up -d
          docker exec app pytest -v
          docker compose down

